# OpenAPI 规范版本号
openapi: 3.0.3

# API 元数据信息
info:
  title: 用户登陆


# 服务器连接信息
servers:
  - url: http://xx.com

# API 的分组标签
tags:

# 对所提供的 API 有效的路径和操作
paths:
  /api/user/login:
    post:
      summary: 用户登陆接口
      operationId: user_login
      requestBody:
        required: true 
        content:  
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: 用户名
                password:
                  type: string
                  description: 密码
      responses:
        '200':
          description: 操作成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  err_code:
                    type: integer
                  data:
                    type: object
                    properties:
                      uid:
                        type: string
                      username:
                        type: string
                      name:
                        type: string
                      groupid:
                        type: integer
                      reg_time:
                        type: string
                      last_login_time:
                        type: string


# 一个包含多种纲要的元素，可重复使用组件
components:

# 声明 API 使用的安全机制
security:

# 附加文档
externalDocs: